### PR TITLE
Sasschaps

### PR DESCRIPTION
**Pull request by sasschaps**
Hello World program written in Golang :)

### CODE REVIEW

**Review by chadwpetersen — CHANGES_REQUESTED** [review]
Rename the folder to go instead of golang. The language is actually go and not golang lol.

**Comment by sasschaps** [comment]
OK cool. Do I have to do that on the command line? Because I actually created that folder manually on Github and now I'm not sure how to rename it :')

**Comment by chadwpetersen** [comment]
Well you mist use vscode and your terminal. Do not use Github to create files and folders.

**Comment by sasschaps** [comment]
Ok, I've renamed it :)

**Pull request merged**
